# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='open_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
