# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodrep', '0002_auto_20180524_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food',
            name='expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='open_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
